### ISSUE TITLE
Crounch Jump with shift+space

### ISSUE THREAD

**Issue by gabrielbuzziv** [TheRagingWampa/PUBG_AHK#13]
Is possible to change the crounch jumo to shift+space?

**Why?** 

- In the most of times you cronch jump you're running.
- When you use space to break the car, sometimes dont break when trigger is only SPACE
- When you type to your friends in steam everytime you press "Space" is adding a C, this is annoying as hell.

How can the trigger be changed?

**Comment by TheRagingWampa** [comment]
Add "<+" to space::c so it looks like "<+shift::c" that makes it use left shift to function. Make sure to not get rid of the "~" before that.
