### ISSUE TITLE
Not working ?

### ISSUE THREAD

**Issue by yoloswagginz13** [TheRagingWampa/PUBG_AHK#2]
So first of all thank you for this script..

But this script isnt working for me.. What am i doing wrong ? Can someone explain me how to use this ?
Maybe im using AHK the wrong way ? Thank you for your help.

**Comment by TheRagingWampa** [comment]
Can you give me some more info on how you are trying to use the script?

**Comment by yoloswagginz13** [comment]
I installed AHK and then the .ahk files who have no programm assigned to it before get executable. I then rightclick on the script for my resolution and click run script.. I start the game then and try to activate it but nothing happens.. What am i doing wrong ? :D thanks for your fast answer !

**Comment by TheRagingWampa** [comment]
Okay I think I know what is going wrong here, the script will suspend itself when the mouse cursor is visible so whenever you are in a menu, inventory, or map ex. you will not be able to interact with the script. The only time you are able to interact with it is when you are able to move your character and are able to look around.

**Comment by yoloswagginz13** [comment]
i was on the little island and tried if it works on the m16 but it doesnt.. what am i missing ?
thanks.

**Comment by FxOxAxD** [comment]
Ok @yoloswagginz13 , by default this is set to off, so I think you forgot to activate it by pressing "b", you should see a tooltip.
You can set it to be on by default changing V_AutoFire to 1
I hope I've helped you.

**Comment by yoloswagginz13** [comment]
you kinda did.. but ofc i was reading the tooltip before :D but that doesnt even work.. ill try to put it on by default.. Thank you both.

**Comment by yoloswagginz13** [comment]
Well i changed that Value now and it still doesnt work... Someone has an idea what im still doing wrong ? :D

**Comment by FxOxAxD** [comment]
If you see the tooltip changing between on and off it means everything is working properly, you should be able to autofire.

**Comment by yoloswagginz13** [comment]
yh basicly the tooltip is not there.. so something is not working for me.. i dont know what im doing wrong :D

**Comment by TheRagingWampa** [comment]
Can you upload the file you are running here?

**Comment by yoloswagginz13** [comment]
[Autofire(1080p).zip](https://github.com/TheRagingWampa/PUBG_AHK/files/1319842/Autofire.1080p.zip)

**Comment by TheRagingWampa** [comment]
Huh, the script is definitely the right one can you check and make sure that it on in the tray when you click run script. 

PS: I put out a simple update that just presses crouch when you jump.

**Comment by nedals** [comment]
I have the exact Same Problem and this isnt my First Script.
I copied the Script 1:1 and it just doesnt work ingame.
Its Not even showing tooltips when Pressing B.
Got the right one for my Resolution.
So There must be a Bug cause im Not the only one experiencing this Problem.
All my other Scripts work flawless.

**Comment by FxOxAxD** [comment]
Make sure you're playing in Window or Full Window Mode.

**Comment by nedals** [comment]
Why?all my other scripts work in Fullscreen mode,so that has nothing to do with it.
fullscreen windowed is not an option cause it introduces input lag.
