### ISSUE TITLE
A little problem

### ISSUE THREAD

**Issue by pacximity** [TheRagingWampa/PUBG_AHK#7]
i read the instructions and its said that disablemousewheel is currently the autofire, but its not working in game. However both autofire are working but with a little problem, when ever i click rmb or numpad 1/0, a little notification shows up and saids "Autofire disable or Autofire enable". its quite annoying as everytime that little thing shows up, it decreases my frame and even worse for fullscreen. it will automatically minimized the game and back to desktop. sorry for my broken english ):

**Comment by pacximity** [comment]
Is it possible where you can disable the notification from ahk or can you make one that doesn't show the notification? one more thing, should i use autofire 1080p if the resolution i use it 1440x900. Thanks for the work man <3

**Comment by TheRagingWampa** [comment]
The resolution is just for the notifications, I'm going to put out an update probably later this week, so I'll make a version that doesn't have any tooltips with it.

On a side note when you say "i read the instructions and its said that disablemousewheel is currently the autofire, but its not working in game." do you mean the disabling of the mouse wheel isn't working in game? It should disable swapping of weapons, but allow scrolling in the map.

**Comment by pacximity** [comment]
i meant the auto fire that you renamed "disablemousewheel" isn't working. The autofire function, not the disable mouse wheel.

**Comment by pacximity** [comment]
one more thing. for some reason pressing rmb or holding it triggers the tooltip as well, is this a problem?

**Comment by TheRagingWampa** [comment]
Yeah that is a reminder for me when I have it on and am about to shoot at distance.
