### ISSUE TITLE
Suggestion, auto aiming

### ISSUE THREAD

**Issue by teck1233** [TheRagingWampa/PUBG_AHK#9]
Can you please add to the script feauture. 
Automatically hold the right mouse button when you shoot (when u holt the left mouse). Thanks.

**Comment by ghost** [comment]
Adding this would make it impossible to actually "hard zoom".

**Comment by teck1233** [comment]
Why? If "hard zoom" = ADS, then you can do just turn off the script when you right-click mouse. Another click will run the script back.
